

# 处理缺失值  {#missing-values}  



## 探索  {#explore-missing}

`drop_na()` 根据列去除带有缺失值的观测：  

```{r}
df <- tibble(x = c(1, 2, NA), y = c("a", NA, "b"), z = c("1", "2", "3"))
df %>% drop_na() # df %>% drop_na(x, y)
df %>% drop_na(x)
```


**Janitor** 中的 `tabyl`

```{r}
tabyl(df, y)
```





## 填充 {#fill-missing}

https://jiangjun.link/post/2018/12/r-missing-data  

用中位数或均值填补缺失值   

```{r,message=F}
library(tidyverse)
df <- tibble(x = c(1, 2, NA, 5, 9, NA),
             y = c(NA, 20, 1, NA, 5, NA),
             z = 5:10)


df %>% 
  mutate_all( ~ ifelse(is.na(.x), median(.x, na.rm = T), .))
```

\@ref(missing-values) 中的 `fill()`:  

```{r}
df <- data.frame(Month = c(1:8, NA, 10), Year = c(2000, rep(NA, 9)), values = c(NA, 12:20))
df
df %>% fill(starts_with("Y"), .direction = "down")
```




或者 `janitor::remove_empty()`  


`full_seq()`，得到完整的序列：  

```{r}
full_seq(c(1, 2, 4, 5, 10), 1)
```


`replace_na()` replace missing values:  

```{r}
df <- tibble(x = c(1, 2, NA), y = c("a", NA, "b"), z = list(1:5, NULL, 10:20))
df %>% mutate(x = replace_na(x, 0))
df %>% replace_na(list(x = 0, y = "unknown"))
```


```{r}
# NULL are the list-col equivalent of NAs
df %>% replace_na(list(z = list(5)))
```

```{r}
df$x %>% replace_na(0)
df$y %>% replace_na("unknown")
```


`visdat::vis_missing()`  

```{r}
library(visdat)
vis_miss(df)
```




more advanced:  mice 或 Amelia


