
# santoku    

https://hughjonesd.github.io/santoku/tutorials/00-visualintroduction.html

```{r}
# devtools::install_github("hughjonesd/santoku")
# library(tidyverse) (load tidyverse before santoku to avoid conflicts)
library(santoku)
```

`cut()` in base R  

```{r}
x <- rnorm(100)
cut(x, 5) %>% table()  # 5 equal intervals
cut(x, -3:3) %>% table()
```

`ntile()` in dplyr:  

```{r}
ntile(x, 5) %>% table()
```




`chop()`

```{r}
chopped <- chop(x, breaks = -5:5)

chopped %>% table()

# chop() returns a factor
tibble(x, chopped)
```

If data is beyond the limits of `breaks`, they will be extended automatically, unless `extend = FALSE`, and values beyond the bounds will be converted to `NA`:  

```{r}
chopped <- chop(x, breaks = -1:1, extend = FALSE)
tibble(x, chopped)
```

To chop a single number into a separate category, put the number twice in `breaks`:

```{r}
x_zeros <- x 
x_zeros[1:5] <- 0

chopped <- chop(x_zeros, c(-1, 0, 0, 1))
tibble(x, chopped)
```

To quickly produce a table of chopped data, use `tab()`:  

```{r}
tab(x, breaks = -3:3)
```

